#######################
# CSS-BOT CONFIG FILE #
#######################

# Discord bot credentials and settings
[discord]
token = "DISCORD-BOT-TOKEN"

# Server settings
[server]
cmd-prefix = "!"

#Color shemes
[colors]
[colors.embed]
color = "#550C18"